# Generated by Django 3.1.5 on 2024-02-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grunge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='playlist_id',
        ),
    ]
